export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_CONTACT_ACTIVE = 'SET_CONTACT_ACTIVE';
export const SET_MOBILE = 'SET_MOBILE';
export const SET_CART_ACTIVE = 'SET_CART_ACTIVE';
export const SET_BADGE_NUMBER = 'SET_BADGE_NUMBER';
export const SET_NAV_LAYOUT = 'SET_NAV_LAYOUT';
